---
- name: Install Composer into the current directory.
  shell: >
    curl -sS https://getcomposer.org/installer | php
    creates={{ composer_path }}

- name: Move Composer into globally-accessible location.
  shell: >
    mv composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: Update Composer to latest version (if configured).
  shell: >
    php {{ composer_path }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated
